version: "3"
services:
  api: 
    image: psahoo2004/fastapi
    ports: 
      - 80:8000
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM} 
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:   # ✅ ensures Postgres starts first
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}   # ✅ added
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: